# Generated by Django 3.0.8 on 2022-09-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='rel7817', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
